### ISSUE TITLE
Qbittorrent Password

### ISSUE THREAD

**Issue by arjung24** [wy580477/Leech-AIO-APP-EX#31] opened 2022-06-20 10:23 UTC
i forgot my qbittorrent password. i can't access the qbittorrent server. is there any way to reset it??

**Comment by wy580477** [comment] 2022-06-20 10:28
> i forgot my qbittorrent password. i can't access the qbittorrent server. is there any way to reset it??

delete 'WebUI\Password_PBKDF2' & 'WebUI\Username=mindfury' lines in config/qBittorrent/config/qBittorrent.conf file.

**Comment by arjung24** [comment] 2022-06-20 10:35
i deleted. but still showing invalid user and pass

i used default user pass

**Comment by wy580477** [comment] 2022-06-20 10:37
> i deleted. but still showing invalid user and pass
> 
> i used default user pass

delete qBittorrent.conf file, then run 'sv restart 1' in ttyd.

**Comment by arjung24** [comment] 2022-06-20 10:41
this came

ok: run: 1: (pid 1263) 0s

**Comment by arjung24** [comment] 2022-06-20 10:43
Thanks brother. it worked

**Comment by arjung24** [comment] 2022-06-20 10:50
brother another issue is qbittorrent is downloading files in assigned folder. rclone job is running well. but i m not getting the files in assigned gdrive folder (/upload). other downloaders are ok.

**Comment by wy580477** [comment] 2022-06-20 10:57
> brother another issue is qbittorrent is downloading files in assigned folder. rclone job is running well. but i m not getting the files in assigned gdrive folder (/upload). other downloaders are ok.

show qbit log

**Comment by arjung24** [comment] 2022-06-20 11:01
[current.txt](https://github.com/wy580477/Leech-AIO-APP-EX/files/8940025/current.txt)

**Comment by arjung24** [comment] 2022-06-20 11:06
brother i found the file location. but how it is possible??
location= /upload/qBittorrent/**some_folder**

**Comment by wy580477** [comment] 2022-06-20 11:06
> [current.txt](https://github.com/wy580477/Leech-AIO-APP-EX/files/8940025/current.txt)

I need more details.

Are you seeing uploaded files in /upload/qBittorret folder in Rclone remote?

How did you assign qBit download folder？

Did qBit ignore qbit-drive-dir setting in script.conf?

**Comment by arjung24** [comment] 2022-06-20 11:08
> > [current.txt](https://github.com/wy580477/Leech-AIO-APP-EX/files/8940025/current.txt)
> 
> I need more details.
> 
> Are you seeing uploaded files in /upload/qBittorret folder in Rclone remote?
> 
> How did you assign qBit download folder？
> 
> Did qBit ignore qbit-drive-dir setting in script.conf?

https://github.com/wy580477/Leech-AIO-APP-EX/issues/31#issuecomment-1160308728

**Comment by wy580477** [comment] 2022-06-20 11:10
> brother i found the file location. but how it is possible?? location= /upload/qBittorrent/**some_folder**

You are downloading files to sub folder of qBit download dir. 

Several days there was a feature request for keeping sub folder to remote path, so there was a change.

**Comment by arjung24** [comment] 2022-06-20 11:12
is it possible to go back to default location (/upload/qBittorrent) brother??

**Comment by arjung24** [comment] 2022-06-20 11:13
> > brother i found the file location. but how it is possible?? location= /upload/qBittorrent/**some_folder**
> 
> You are downloading files to sub folder of qBit download dir.
> 
> Several days ago there was a feature request for keeping sub folder to remote path, so there was a change.

i was urging for that. ha ha ha.

**Comment by wy580477** [comment] 2022-06-20 11:13
> is it possible to go back to default location (/upload/qBittorrent) brother??

Don't change default download folder, then files shoud be uploaded to /upload/qBitorrent folder.

**Comment by arjung24** [comment] 2022-06-20 11:15
> > is it possible to go back to default location (/upload/qBittorrent) brother??
> 
> Don't add sub path to default download folder, then files shoud be uploaded to /upload/qBitorrent folder.

where to edit

**Comment by wy580477** [comment] 2022-06-20 11:16
> idk how the location got changed. i want to set the location to /upload/qBittorrent

![image](https://user-images.githubusercontent.com/98247050/174590057-c061bff6-2228-48cf-8fd8-3d2cfaed395a.png)

Change download path back to default path.

**Comment by wy580477** [comment] 2022-06-20 11:22
> my settings are as u shown. but i m not getting the real fault of sub location

Show me uploaded path.

**Comment by arjung24** [comment] 2022-06-20 11:30
sorry brother i am not getting u. do u want to know my drive uploaded location for qbittorrent??
if yes then it's below
![Screenshot (5)](https://user-images.githubusercontent.com/68998000/174592532-930bdc23-63d3-409a-a471-5a22d38ed970.png)

**Comment by wy580477** [comment] 2022-06-20 11:33
> sorry brother i am not getting u. do u want to know my drive uploaded location for qbittorrent?? if yes then it's below ![Screenshot (5)](https://user-images.githubusercontent.com/68998000/174592532-930bdc23-63d3-409a-a471-5a22d38ed970.png)

Are you download a torrent which contains a folder?
If your torrent contains a folder, It's working correctly. Files will be uploaded to a folder named with qbit task name.

**Comment by arjung24** [comment] 2022-06-20 11:36
no no.
all files and folders are downloading to inside this "Knuckle(2011)[1080p] [Webrip] [YTS.MX]" folder.
that's the problem

**Comment by wy580477** [comment] 2022-06-20 12:11
> no no. all files and folders are downloading to inside this "Knuckle(2011)[1080p] [Webrip] [YTS.MX]" folder. that's the problem

![image](https://user-images.githubusercontent.com/98247050/174598856-f8bca304-6f43-4b2f-90a5-537a5ccb43d9.png)

I can't reproduce your issue.

**Comment by wy580477** [comment] 2022-06-20 12:24
> ok brother. Thanks a lot. Please check ttyd. yt-dlp downloaded the files and instantly deleting the file also from drive

It deleted seperate video & audio files after merging. The merged file is fine.

![image](https://user-images.githubusercontent.com/98247050/174600902-1f6d91c7-76ff-48f2-a0f3-13eb5e2d7df7.png)

**Comment by arjung24** [comment] 2022-06-20 12:34
i am not getting the downloaded file in drive. that's why asked. olivetin working fine

**Comment by wy580477** [comment] 2022-06-20 12:35
> i am not getting the downloaded file in drive. that's why asked. olivetin working fine

Are you using dlpr alias? Go to videos folder.

**Comment by arjung24** [comment] 2022-06-20 12:37
> > i am not getting the downloaded file in drive. that's why asked. olivetin working fine
> 
> Are you using dlpr alias? Go to videos folder.

files are downloaded to root folder. outside videos folder

**Comment by arjung24** [comment] 2022-06-20 12:40
![Screenshot (7)](https://user-images.githubusercontent.com/68998000/174603646-e196c08e-f00e-42d5-a40e-021c00838f05.png)

**Comment by arjung24** [comment] 2022-06-20 12:47
do i need to setup anything to access this url??

**Comment by arjung24** [comment] 2022-06-20 12:54
> > do i need to setup anything to access this url??
> 
> You need a proxy client which support Vmess protocol. Then you can route your network traffic to your heroku app.
> 
> See here:
> 
> https://github.com/XTLS/Xray-core#gui-clients
> 
> https://www.v2fly.org/en_US/awesome/tools.html#third-party-gui-clients

brother i generated v2ray vmess UUID. but now what to do idk

**Comment by arjung24** [comment] 2022-06-20 13:09
i am using android app to strat the service.will it work??

**Comment by wy580477** [comment] 2022-06-20 13:11
> i am using android app to strat the service.will it work??

See log in your client app or Xray log in your heroku app log folder.

**Comment by arjung24** [comment] 2022-06-20 13:16
after starting the service from app. i can't access any website. why it'd not working brother. what could be the possible error?? client app log saying failed.

**Comment by wy580477** [comment] 2022-06-20 13:18
> after starting the service from app. i can't access any website. why it'd not working brother. what could be the possible error?? client app log saying failed.

Please add detail info when asking questions.

Show your client config (mask your heroku address and UUID)

**Comment by arjung24** [comment] 2022-06-20 13:23
> > after starting the service from app. i can't access any website. why it'd not working brother. what could be the possible error?? client app log saying failed.
> 
> Please add detail info when asking questions.
> 
> Show your client config (mask your heroku address and UUID)

![IMG_20220620_192153](https://user-images.githubusercontent.com/68998000/174611348-ea4dff1f-3222-4143-89a4-a3534e35c09f.jpg)
![IMG_20220620_192227](https://user-images.githubusercontent.com/68998000/174611357-8bb9f854-b9c7-48c9-92e5-dc0fe27deed3.jpg)

**Comment by wy580477** [comment] 2022-06-20 13:25
Enable tls. 

Or Change to 80 port if keeping tls disabled.

**Comment by arjung24** [comment] 2022-06-20 13:42
> > > Enable tls.
> > > Or Change to 80 port if keeping tls disabled.
> > 
> > 
> > Thanks a lot brother. it's working fine.
> > just suggest me good Vmess UUID generator/website please
> 
> Use ttyd
> 
> ![image](https://user-images.githubusercontent.com/98247050/174613821-20fb241a-3dff-4776-b4fe-b246d74b0a8b.png)

is it possible to know that generated uuid is from which country??
can i generate randomly anytime from ttyd following this command??

**Comment by wy580477** [comment] 2022-06-20 13:45
> 
> is it possible to know that generated uuid is from which country?? 

Not possible.

> can i generate randomly anytime from ttyd following this command??

You need to run "apk add uuidgen" everytime after dyno restarted.

There is no need to change UUID frequently. It's just a very strong password.

**Comment by arjung24** [comment] 2022-06-20 13:49
i just want to use hotstar.com using vmess proxy. it needs indian ip.

**Comment by wy580477** [comment] 2022-06-20 13:50
> i just want to use hotstar.com using vmess proxy. it needs indian ip.

Not possible. Heroku free tier only has us and eu servers.

**Comment by wy580477** [comment] 2022-06-20 13:56
> do i need to be connected in my mobile client app as long as i want to use that UUID??

No, you can reuse it as long as you like.

**Comment by arjung24** [comment] 2022-06-20 13:58
Thanks a lot brother. That was a massive help today.
Lots of things are solved. Many many thanks.

**Comment by arjung24** [comment] 2022-06-21 09:06
Brother don't get me wrong. But is it possible to add ripme in ur repo. If possible please add. It would be a great help brother.

**Comment by SonaliBendre** [comment] 2022-06-21 17:42
cloudflare was down so you lost your config

**Closed** 2022-07-03 00:08 UTC
